### ISSUE TITLE
`internal/docker-scratch-push` seems to be broken

### ISSUE THREAD

**Issue by fd** [wercker/support#102]
I get the following error:

```
API error (500): Untar fork/exec /usr/bin/docker: argument list too long
```

![screen shot 2015-08-13 at 10 18 52](https://cloud.githubusercontent.com/assets/591/9245483/ba43c13c-41a4-11e5-98be-793a11757ba6.png)

```yaml
  - internal/docker-scratch-push:
      username: $DOCKER_USERNAME
      password: $DOCKER_PASSWORD
      tag: $APP_VERSION
      repository: my/repo
      registry: https://registry.hub.docker.com
      ports: "80"
      cmd: /bin/app serve
```
