### ISSUE TITLE
Build's all failing with `The step "code" was not found`

### ISSUE THREAD

**Issue by earnaway** [wercker/support#107]
As of today (19 August '15), all my wercker builds are failing with the error:

```The step "code" was not found```

Has something changed with the parsing of the wercker yml file?

**Comment by corbinu** [comment]
+1 .... seriously this is a HUGE problem and needs to be fixed ASAP!

**Comment by flenter** [comment]
The problem lies with a previous allowed way of indenting. I've created a gist to show where the problem lies.


The step is probably indented like so:
```
build:
  steps: 
    - script:
      name: failing
      code: |
        echo "step"
```

The indentation should be changed to:

```
build:
  steps: 
    - script:
        name: failing
        code: |
          echo "step"
```
