### ISSUE TITLE
The validator does not recognize the internal/docker-push step

### ISSUE THREAD

**Issue by FrancisToth** [wercker/support#113]
I'm trying to validate a wercker.yml file with the [validator](http://old-devcenter.wercker.com/articles/werckeryml/validate.html), and it keeps telling me that the [internal/docker-push](http://devcenter.wercker.com/docs/containers/pushing-containers.html) step is not in the registry : 

"Oops Step internal/docker-push does not exist in the registry."

Is there any reason for that ?

Here's the yml file :
```
box: mies/java7-oracle@0.0.1

build:
  box: 1science/sbt
  steps:
    - script:
        name: Build project
        code: cd $WERCKER_SOURCE_DIR && sbt test package -Dsbt.ivy.home=$WERCKER_CACHE_DIR/.ivy2/

deploy:
  steps:
    - internal/docker-push:
        username: $USERNAME
        password: $PASSWORD
        tag: my-amazing-tag
        repository: turing/bar
        registry: https://registry.hub.docker.com
```
