### ISSUE TITLE
"Context Canceled" error when deploying on AWS-code deploy

### ISSUE THREAD

**Issue by FrancisToth** [wercker/support#114]
Hi ! I'm trying to deploy a jar on AWS-code-deploy through wercker but it keeps throwing an error saying "Context canceled", any idea ? I've asked the support, but still no answer so far. Here's my build file : 
```
build:
  box: 1science/sbt:0.13.8-oracle-jre-7
  steps:
    - script:
      name: Build project
      code: cd $WERCKER_SOURCE_DIR && sbt test package -Dsbt.ivy.home=$WERCKER_CACHE_DIR/.ivy2/

deploy:
  box: 1science/java:oracle-jre-7
  steps:
    - script:
      name: Install AWS CLI
      code: |
        apk-install python
        wget "https://bootstrap.pypa.io/get-pip.py" -O /dev/stdout | python
        pip install awscli

    - internal/docker-push:
      username: $DOCKER_REGISTRY_USERNAME
      password: $DOCKER_REGISTRY_PASSWORD
      entrypoint: /bin/sh -c "java -jar /pipeline/output/onescience-rest-api_*.jar"
      tag: latest
      ports: "8087"
      repository : $DOCKER_REPOSITORY
      registry: $DOCKER_REGISTRY

    - nhuray/aws-code-deploy:
      name: Deploy on AWS with Code Deploy
      # Authentication
      key:  $AWS_ACCESS_KEY_ID
      secret: $AWS_SECRET_ACCESS_KEY
      region: $AWS_DEFAULT_REGION
      # Application
      application-name: onescience-rest-api
      application-version: ${WERCKER_GIT_COMMIT:0:7}
      # Deployment config
      deployment-config-name: $AWS_CODE_DEPLOY_DEPLOYMENT_CONFIG_NAME
      # Deployment group
      deployment-group-name: $AWS_CODE_DEPLOY_DEPLOYMENT_GROUP_NAME
      service-role-arn: $AWS_CODE_DEPLOY_SERVICE_ROLE_ARN
      ec2-tag-filters: $AWS_CODE_DEPLOY_EC2_TAG_FILTERS
      # S3
      s3-bucket: $AWS_CODE_DEPLOY_S3_BUCKET
      s3-source: deploy/aws
```
