### ISSUE TITLE
add-to-known_hosts failed

### ISSUE THREAD

**Issue by drakeguan** [wercker/support#120]
Here is the *deploy* part of wercker.yml

```
box: debian

deploy:
  steps:
    - add-to-known_hosts:
      hostname: ooxx.asdf
      local: true
```

And the message is:

```
export WERCKER_STEP_ROOT="/pipeline/add-to-known_hosts-ed63fafb-18f8-4e41-bdc2-e5757ff48b13"
export WERCKER_STEP_ID="add-to-known_hosts-ed63fafb-18f8-4e41-bdc2-e5757ff48b13"
export WERCKER_STEP_OWNER="wercker"
export WERCKER_STEP_NAME="add-to-known_hosts"
export WERCKER_REPORT_NUMBERS_FILE="/report/add-to-known_hosts-ed63fafb-18f8-4e41-bdc2-e5757ff48b13/numbers.ini"
export WERCKER_REPORT_MESSAGE_FILE="/report/add-to-known_hosts-ed63fafb-18f8-4e41-bdc2-e5757ff48b13/message.txt"
export WERCKER_REPORT_ARTIFACTS_DIR="/report/add-to-known_hosts-ed63fafb-18f8-4e41-bdc2-e5757ff48b13/artifacts"
export WERCKER_ADD_TO_KNOWN_HOSTS_HOSTNAME="ooxx.asdf"
source "/pipeline/add-to-known_hosts-ed63fafb-18f8-4e41-bdc2-e5757ff48b13/run.sh" < /dev/null
/root/.ssh does not exists, creating it
/root/.ssh/known_hosts does not exists, touching it and chmod it to 644
/pipeline/add-to-known_hosts-56dfb61c-f801-4cf1-945a-b031b161c7e1/run.sh: line 46: ssh-keyscan: command not found
```

**ssh-keyscan: command not found**

**Comment by drakeguan** [comment]
This issue is solved by two steps:

* Make sure **local: true**.
* Install openssh-client through **install-packages**.

Updated wercker.yml
```
box: debian

deploy:
  steps:
    - install-packages:
      packages: openssh-client
    - add-to-known_hosts:
      hostname: ooxx.asdf
      local: true
```
