### ISSUE TITLE
npm install step doesn't install devDependencies in dev pipeline

### ISSUE THREAD

**Issue by mstade** [wercker/support#133]
When running the `npm-install` step in the dev pipeline, the `NODE_ENV` env variable is set to `production`. This means any dependency listed in `devDependencies` in package.json will be ignored, which is counter intuitive. The workaround is to add a script step right before the `npm-install` step, that sets up the `NODE_ENV` variable correctly:

```yaml
dev:
  steps:
    - script:
        code: export NODE_ENV=development
    - npm-install
```

It would probably make sense for wercker to set the `NODE_ENV` to some value other than `production` in the dev pipeline, or even avoid setting it altogether.

**Comment by hatchan** [comment]
The `npm-install` step doesn't set the `NODE_ENV`. This is probably done in the Docker container itself. 

So the workaround that you specified is probably the easiest. You could also create a new container, based of the container that you are using, and just change `NODE_ENV`.

**Comment by mstade** [comment]
Of course, that makes sense – thanks! My apologies for the spam.

**Comment by mohamnag** [comment]
just stumbled on this and for reference you could also set env variables on box:
```
box:
  id: node
  env:
    NODE_ENV: test
```
