### ISSUE TITLE
internal/docker-push: support for workdir

### ISSUE THREAD

**Issue by JeanMertz** [wercker/support#146]
I'd like to define something like:

```yaml
- internal/docker-push:
    username: $USERNAME
    password: $PASSWORD
    tag: $IMAGE_TAG
    workdir: /app
    entrypoint: /docker-entrypoint
    cmd: puma
    ports: "80"
```

using `workdir` to not have to cd into the correct directory every time I enter (or start) the container.
