### ISSUE TITLE
multiple boxes in deploy pipeline

### ISSUE THREAD

**Issue by JeanMertz** [wercker/support#158]
The docs mention [per-pipeline containers](http://devcenter.wercker.com/docs/pipelines/per-pipeline-containers.html). How about per-deploy-target containers?

```yml
deploy:
  box: ruby
  registry:
    - script: ...
  cron:
    box: jeanmertz/whenever
    - script: ...
```
