### ISSUE TITLE
How to configure Postgis with wercker ?

### ISSUE THREAD

**Issue by zedtux** [wercker/support#166]
I have Ruby On Rails application, using Postgres + Postgis.

My `wrecker.yml` file:

```
box: ruby:2.1.7

services:
  - id: helmi03/docker-postgis

# See more about services on our devcenter:
# http://devcenter.wercker.com/articles/services/
build:
  steps:
    # Downgrade Rubygems (see https://github.com/wercker/support/issues/161#issuecomment-155731186)
    - script:
      name: downgrade GemFile
      code: gem update --system 2.4.8

    # A step that executes `bundle install` command
    # All the options of Bundler can be set only via environment variables.
    # You have to edit the project on wercker.com and set the variables.
    # To see the list of possible options:
    # https://github.com/wercker/step-bundle-install/blob/master/run.sh
    - bundle-install

    # A step that installs the required packages
    - install-packages:
      packages: postgresql-9.4-postgis-scripts

    - script:
      name: Debug
      code: |
        ls -al /usr/share/postgresql/9.4/extension/postgis.control
        cat /usr/share/postgresql/9.4/extension/postgis.control

    # A step that prepares the database.yml using the database in services
    - rails-database-yml

    - script:
      name: create table
      code: |-
        echo "$(pg_config --sharedir)/contrib/"
        createdb mydb
        createdb -E UTF8 template_postgis
        psql -d postgres -c "UPDATE pg_database SET datistemplate='true' WHERE datname='template_postgis';"
        psql -d template_postgis -f $POSTGIS_SQL_PATH/postgis.sql
        psql -d template_postgis -f $POSTGIS_SQL_PATH/spatial_ref_sys.sql
        psql -d template_postgis -c "GRANT ALL ON geometry_columns TO PUBLIC;"
        psql -d template_postgis -c "GRANT ALL ON geography_columns TO PUBLIC;"
        psql -d template_postgis -c "GRANT ALL ON spatial_ref_sys TO PUBLIC;"

    # A step that describes the running environment
    - script:
      name: echo ruby information
      code: |
        echo "ruby version $(ruby --version) running"
        echo "from location $(which ruby)"
        echo "gem list: $(gem list)"

    # A step that loads the database schema in order to run the tests
    - script:
      name: Set up db
      code: bundle exec rake db:create db:migrate RAILS_ENV=test

    # A step that runs the tests (RSpec)
    - script:
      name: rspec
      code: bundle exec rspec
```

Here what I get as error is the following:

```
Auto detecting service
failed: Unable to auto detect service; please set "service" option
```

And this is due to the fact that the Postgres + Postgis image is named `docker-postgis` so that the environment variables are named `DOCKER_POSTGIS_PORT_5432_TCP_ADDR` and `DOCKER_POSTGIS_PORT_5432_TCP_PORT` which makes the [rails-database-yml](https://github.com/wercker/step-rails-database-yml/blob/242dd9cbfc05178957f4a9338cffd12c92336c8a/run.sh#L93) step failing as it can find the variables.

Is there a way to "rename" the docker image, like we can do with the docker `--link` flag in order to have the right environment variables ?

**Comment by zedtux** [comment]
Help please ?

**Comment by flenter** [comment]
Why not add a script step before the `- rails-database-yml` step that creates the environment variables that the rails-database-yml step expects. 

```
...
build:
  steps:
    ...

    - script: 
        name: create postgres env vars
        code: |
          export POSTGRES_PORT_5432_TCP_PORT=$DOCKER_POSTGIS_PORT_5432_TCP_PORT
          export POSTGRES_PORT_5432_TCP_ADDR=$DOCKER_POSTGIS_PORT_5432_TCP_ADDR

    - rails-database-yml
    ...
```

I'm no rails expert, so I don't know if you need to specify a different adapter/engine or something.

**Comment by zedtux** [comment]
Thank you @flenter, it's helpful but I have now the following error :

```
createdb: could not connect to database template1: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
```

It seems that the DB is not running ... 

Setting

```
services:
  - id: helmi03/docker-postgis
```

at the begin of the `wercker.yml` file shouldn't start the DB automatically ?

**Comment by zedtux** [comment]
Alright, I finally got it working after couple of hours investigating ...

In case it could help someone later, here is my working `wrecker.yml` file :

```yaml
box: ruby:2.1.7

services:
  - id: neowaylabs/postgis

# See more about services on our devcenter:
# http://devcenter.wercker.com/articles/services/
build:
  steps:
    # Downgrade Rubygems (see https://github.com/wercker/support/issues/161#issuecomment-155731186)
    - script:
      name: downgrade GemFile
      code: gem update --system 2.4.8

    # A step that executes `bundle install` command
    # All the options of Bundler can be set only via environment variables.
    # You have to edit the project on wercker.com and set the variables.
    # To see the list of possible options:
    # https://github.com/wercker/step-bundle-install/blob/master/run.sh
    - bundle-install

    # A step that installs the required packages
    - install-packages:
      packages: postgresql-9.4-postgis-scripts

    - script:
      name: create postgres env vars
      code: |
        export POSTGRES_PORT_5432_TCP_ADDR=$POSTGIS_PORT_5432_TCP_ADDR
        export POSTGRES_PORT_5432_TCP_PORT=$POSTGIS_PORT_5432_TCP_PORT
        export POSTGRES_ENV_POSTGRES_USER=docker
        export POSTGRES_ENV_POSTGRES_PASSWORD=postgis
        export WERCKER_POSTGRESQL_ADAPTER=postgis

    - script:
      name: Debug
      code: |
        ls -al /usr/share/postgresql/9.4/extension/postgis.control
        cat /usr/share/postgresql/9.4/extension/postgis.control
        echo "Env: "
        env

    - rails-database-yml

    # A step that describes the running environment
    - script:
      name: echo ruby information
      code: |
        echo "ruby version $(ruby --version) running"
        echo "from location $(which ruby)"
        echo "gem list: $(gem list)"

    # A step that loads the database schema in order to run the tests
    - script:
      name: Set up db
      code: |
        export PGHOST=$POSTGRES_PORT_5432_TCP_ADDR
        export PGPORT=$POSTGRES_PORT_5432_TCP_PORT
        export PGUSER=docker
        export PGPASSWORD=postgis
        echo "Recreating template1 from template0 ..."
        psql -c "UPDATE pg_database SET datistemplate = FALSE WHERE datname = 'template1';"
        psql -c "DROP DATABASE template1;"
        psql -c "CREATE DATABASE template1 WITH TEMPLATE = template0 ENCODING = 'UNICODE';"
        psql -c "UPDATE pg_database SET datistemplate = TRUE WHERE datname = 'template1';"
        echo "Creating application database ..."
        bundle exec rake db:create db:migrate RAILS_ENV=test

    # A step that runs the tests (RSpec)
    - script:
      name: rspec
      code: bundle exec rspec
```
