### ISSUE TITLE
Store-container after-steps never runs

### ISSUE THREAD

**Issue by pimterry** [wercker/support#168]
I'm trying to debug a weird issue with my build (probably unrelated, but just in case: for some reason the script I have to upload my build over FTP onto the linked selenium server container has stopped working, only remotely on wercker, not locally), so I'm trying to add a store container step, so I can pull down the failing builds and see what's going on.

Unfortunately though, the store-container step never runs. It's marked as having not run in the UI, and I can't pull anything down.

Example build: https://app.wercker.com/#buildstep/564dc36e3468a4e63d02ffbb

My whole wercker.yml looks like:

```yaml
box: pimterry/node-karma
build:
    steps:
        - script:
            name: Print env (for debugging)
            code: env
        - npm-install
        - script:
            name: Install bower
            code: npm install -g bower
        - script:
            name: Install packages from Bower
            code: bower install --allow-root
        - script:
            name: print env
            code: env
        - grunt:
            tasks: ci-test
            fail-on-warnings: true
    after-steps:
        - internal/store-container

    services:
        - pimterry/selenium-chrome-ftp

deploy:
    steps:
        - script:
            name: Configure git
            code: |-
              git config --global user.email "contact@buildfocus.io"
              git config --global user.name "wercker-build"
        - grunt:
            tasks: release
```

The after-steps section is what I've just added to do this, but it doesn't seem to work. Is there anything else required, or am I missing something somewhere?
