### ISSUE TITLE
Build fails with version 1.0.85

### ISSUE THREAD

**Issue by emmenko** [wercker/support#17]
Looks like latest release doesn't work. 
I'm having this issue both locally and on your system:

```bash
$ wercker build
key path /Users/emmenko/.boot2docker/certs/boot2docker-vm/key.pem
############ Executing Pipeline ############

============== Running Step ===============
setup environment
===========================================
Running wercker version: 1.0.85 (Compiled at: 2015-03-27T23:15:39Z, Git commit: 98b0bab04eb5386a6655b29ca8491c82fab9f7aa)
panic: interface conversion: interface is bool, not string [recovered]
	panic: interface conversion: interface is bool, not string [recovered]
	panic: interface conversion: interface is bool, not string
```

![screen shot 2015-03-28 at 15 37 20](https://cloud.githubusercontent.com/assets/1110551/6881454/fd4ff636-d560-11e4-8c74-cfe7829ab266.png)

My `wercker.yml`

```yml
box: emmenko/nodejs-karma:v0.1.2
# Build definition
build:
  # The steps that will be executed on build
  steps:
    - npm-install
    - npm-test
  after-steps:
    - hipchat-notify:
        token: $HIPCHAT_TOKEN
        room-id: $HIPCHAT_ROOM_ID
        on: failed
```

I'm using a docker container and I have the `Ewok` stack enabled.

**Comment by mies** [comment]
this is odd, the issue seems to be with the after-step, removing that section does away with the error. we need some further investigation to debug what's going on though. /cc @termie

**Comment by emmenko** [comment]
Ah ok, let me know if you need anything else. Thanks for investigating! :+1:

**Comment by hatchan** [comment]
This bug is caused by the `on` property. 

`on` is interpreted as a boolean value in yaml. All these properties contain a boolean `true` when parsed:

```
property1: true
property2: on
property3: yes
```

Somehow our yaml parsing library is treating the property name as a boolean, even though the described behaviour should not apply to propertynames.

Current workaround is to wrap the `on` keyword in quotes: 

```
box: emmenko/nodejs-karma:v0.1.2
# Build definition
build:
  # The steps that will be executed on build
  steps:
    - npm-install
    - npm-test
  after-steps:
    - hipchat-notify:
        token: $HIPCHAT_TOKEN
        room-id: $HIPCHAT_ROOM_ID
        "on": failed
```

Will file a bug with package we're using.
