### ISSUE TITLE
Multiple services using the same image

### ISSUE THREAD

**Issue by F21** [wercker/support#193]
Some services such as HDFS and kafka have a few different parts. In the case of HDFS, there are datanodes, namenodes and journal nodes for a typical HA cluster.

I would like to be able to spin up multiple instances of say the datanode images (HDFS usually requires 3 datanodes at a minimum) during testing.

I think the following would be a nice way to achieve this in the `wercker.yml`:

```yml
services:
  - id: dn1
    image: f21global/hdfs-datanode
    env:
      - ...
  - id: dn2
    image: f21global/hdfs-datanode
    env:
      - ...
```
