### ISSUE TITLE
ERROR Failed to push: API error (404): no such id: 

### ISSUE THREAD

**Issue by cescoferraro** [wercker/support#199]
```
    - script:
        name: set env
        code: |
          # define environment variables
          export DOCKER_USERNAME="cescoferraro"
          export DOCKER_PASSWORD="xxxx"
deploy:
    steps:
    - internal/docker-scratch-push:
        # use them in the internal steps
        username: $DOCKER_USERNAME
        password: $DOCKER_PASSWORD
        cmd: ./web/bin runserver
        tag: latest
        ports: "9000"
        repository: cescoferraro/wercker
        registry: https://registry.hub.docker.com
```

```
--> Running step: docker scratch'n'push
Pushing image for tag  latest
ERROR Failed to push: API error (404): no such id: b306a8397389a97b3c37c9c3c0d75c09160579eeb3421e093e76881e0c943787
Additional information:
```

- wercker environment: local
- OS: ubuntu and mac
- Docker environment: native and boot2docker
- Docker machine driver used: virtualbox

Using docker 10

```
cesco@Laptop: ~/code/go/src/bitbucket.org/cescoferraro/templatego on master [!?]
$ docker version
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.6
 Git commit:   c3959b1
 Built:        Tue Feb 23 21:12:32 UTC 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 20:39:58 2016
 OS/Arch:      linux/amd64
```

**Comment by faiq** [comment]
hey thanks for reporting! unfortunately docker 1.10 changed the way the build scratch image id's, so we'll get on this ASAP. we're tracking the progress of the issue here https://github.com/wercker/wercker/issues/92

as a quick fix around you can either rollback your docker version or use the `docker-push-step` with a really small base box such as alpine.

**Comment by cescoferraro** [comment]
would you care to provide a quick example?
As I understand docker-push-step will push the golang box which inside I am currently build my software.

**Comment by faiq** [comment]
thanks for your patience @cescoferraro 

You can accomplish this by using the `--artifacts` option when you use the wercker build step. The command for this would be `wercker build --artifacts`. This will populate your binaries inside `./.wercker/latest/output` 

Then you can run `wercker deploy`, which will look for this folder and copy the items over into a minimal container you set in the deploy target.

Sorry for the inconvenience

**Comment by cescoferraro** [comment]
Cool @faiq ! I got this to work fine but stumbled on other problems that you might help me with or/and help you guys. Do not take me the wrong way! I <3 wercker and anything that makes me ensure how amazing  Golang is!

1 - $WERCKER_OUTPUT_DIR is /pipeline/source but since the internal/docker-push step cmd option wont allow me to run from the current directory like `./bin runserver` I need to user `/pipeline/source/bin runserver` which make my go templates to fail. So I need the pointless cp  step like below.


~~2- All the kubernetes steps I could find on the registry download the whole kubernetes project tarball and execute them inside the container.  Apart from that being freakishly  resource wise, the kubectl binary, the only one we need, is liked to libc.c as well as any golang app; Making really hard to run on minimal containers. Because alpine and busybox usually use musl instead gnu libc. [This image works](https://github.com/blang/golang-alpine-docker) but 200MB is not small enough for me, although it looks good for my build pipeline. It is also worth mention that Curl is also a dependency, but can be ignored both because it is light weight and it is needed only after the container is already pushed to the registry. Do you know any others images? A wercker API that couldproxy those  sorts of kubernetes/mesos  requests might be cool.~~

As of typing this I found joeshaw/busybox-nonroot. IT WORKS!

3 - My . wercker folder (>100GB) on a Ubuntu machine got so big that the whole OS stopped working. How do I avoid these problem? I notice the that the tool keeps ALL build data. Is there a cleanup tool embedded on wercker? Do I need more than the last build on my system?


```
    - script:
        name: scratch folder
        code: |
          mv ./web/bin $WERCKER_OUTPUT_DIR
          mv ./web/templates/ $WERCKER_OUTPUT_DIR
          mv ./web/static/ $WERCKER_OUTPUT_DIR
          mv ./web/config.yaml $WERCKER_OUTPUT_DIR
          mv ./kube $WERCKER_OUTPUT_DIR
  deploy:
    box:
      id: joeshaw/busybox-nonroot
      cmd: /bin/ash
    steps:

        - script:
            name: list files
            code: |
              cp -R templates/ /templates
              cp -R static/ /static
              cp -R kube/ /kube

        - internal/docker-push:
            username: cescoferraro
            password: HO.HO.HO.HO
            tag: latest
            cmd: /pipeline/source/bin runserver
            ports: "9000"
            repository: cescoferraro/templatego
            registry: https://registry.hub.docker.com


        - kubectl:
            insecure-skip-tls-verify: true
            command: -s="HO.HO.HO.HO:8080" create -f kube/svc.yaml
```

**Comment by AlmogBaku** [comment]
Also here for me- now it's almost 2/3 times fails:
```
docker scratch'n'push
API error (404): no such id: 4f4ef940741615efb04bbd3427f3e030c796bbd01e9cefb11b7ce5c516125ace```

```
        - internal/docker-scratch-push:
            aws-access-key: $AWS_ACCESS_KEY_ID
            aws-secret-key: $AWS_SECRET_ACCESS_KEY
            aws-region: $AWS_REGION
            aws-registry-id: $AWS_REGISTRY_ID
            repository: $WERCKER_GIT_REPOSITORY
            entrypoint: ./main
            tag: $WERCKER_GIT_COMMIT
            ports: "8080"
```

**Comment by eeh** [comment]
me too, however, I'm on quay.io:
    - internal/docker-scratch-push:
        username: $DOCKER_USERNAME
        password: $DOCKER_PASSWORD
        tag: latest
        repository: quay.io/eeh0/truemost-admin-react
        registry: https://quay.io
        volumes: /dist/admin-react
        cmd: /sh

**Comment by scheeles** [comment]
Same here:
```
 - internal/docker-scratch-push:
        name: push to docker hub as $WERCKER_GIT_COMMIT
        cmd: /sh
        username: $USERNAME
        password: $PASSWORD
        tag: $WERCKER_GIT_COMMIT
        working-dir: /opt
        repository: $WERCKER_GIT_REPOSITORY
        registry: https://registry.hub.docker.com
```

 I saw it was resolved in #137 but it's still not working on https://app.wercker.com
