### ISSUE TITLE
Cache broken on hosted wercker?

### ISSUE THREAD

**Issue by moritzzimmer** [wercker/support#202]
It seems like the cache isn't used on the wercker hub in our context anymore, because Gradle dependencies and the wrapper itself aren't cached anymore when executing a pipeline (either build or deploy). It has been working in the past and still does locally using docker-machine.

Any thought why?

Additional information:
- wercker environment: hosted

Relevant part of the wercker.yml:
```
box: 
    id: java:8u66-jdk
    env:
        GRADLE_USER_HOME: $WERCKER_CACHE_DIR
        SONAR_USER_HOME: $WERCKER_CACHE_DIR/.sonar
build:
    steps:
        - script:
            name: build and test app
            code: |
                    ./gradlew --full-stacktrace clean check sonarqube elasticbeanstalkZip
deploy:
    box:
        id: weltn24/eb-deployer
        env:
            GRADLE_USER_HOME: $WERCKER_CACHE_DIR
   steps: ...(some gradle here as well)
```

Output:
```
Downloading https://services.gradle.org/distributions/gradle-2.12-bin.zip
..
Unzipping /pipeline/cache/wrapper/dists/gradle-2.12-bin/avhnk0p45wmm16bas931at19r/gradle-2.12-bin.zip to /pipeline/cache/wrapper/dists/gradle-2.12-bin/avhnk0p45wmm16bas931at19r
Set executable permissions for: /pipeline/cache/wrapper/dists/gradle-2.12-bin/avhnk0p45wmm16bas931at19r/gradle-2.12/bin/gradle
Starting a new Gradle Daemon for this build (subsequent builds will be faster).
Parallel execution with configuration on demand is an incubating feature.
Download https://jcenter.bintray.com/org/springframework/boot/spring-boot-gradle-plugin/1.3.2.RELEASE/spring-boot-gradle-plugin-1.3.2.RELEASE.pom
...
```
