### ISSUE TITLE
new step does can't be found

### ISSUE THREAD

**Issue by Morriz** [wercker/support#203]
I created a step with settings put to the old context. I deployed it to the wercker directory, and it showed up in the listing. However, I can't seem to use it:

```
The step "morriz/step-kubectl@1.2.0" was not found
```

I later found that I could set the repository access differently in settings, as opposed to the 'recommended' way: "Wercker will check out the code without using an ssh key". So I chose that and rebuilt. Still no dice.

**Comment by Morriz** [comment]
Btw, I use it like this in my app wercker.yaml, just like I did with wercker's own `kubectl`:
```
deploy:
  box: node:5.4-slim
  # Targets:
  rolling-update:
    - morriz/step-kubectl@1.2.0:
```    

It is a clone of that exact same step, so I should be using it the same way no?
