### ISSUE TITLE
Pulling a private image from Google Container Engine

### ISSUE THREAD

**Issue by roelvanhintum** [wercker/support#204]
For some reason gcr gives me a 400 response when i'm trying to use on of my private images. Am i missing something here? Documentation only covers quay.

(replaced key and repo for security reasons)
```
deploy:
    box:
        id: eu.gcr.io/_KEY_/_REPO_
        username: _json_key
        password: $GCR_KEY_FILE
        email: $GCR_SERVICE_EMAIL
        tag: latest
        registry: https://eu.gcr.io
```

Wercker doesn't tell me more than:
```
GET https://eu.gcr.io/v1/repositories/_KEY_/_REPO_/images returned 400
```

**Comment by faiq** [comment]
@roelvanhintum try running this with a workflows enabled project on wercker. this functionality is also available through https://github.com/wercker/wercker as well, but doing so is a bit more involved. let me know if you need more help!

**Comment by MichaelVorster** [comment]
Hi,

I am having the same problem, i.e., I am also getting the same 400 error.  I am following the wercker documentation given here: http://devcenter.wercker.com/docs/containers/private-containers.html.

This is when I try to run a build step locally.  I don't see how running this with a workflows enabled project on wercker will solve the problem.

Kind regards,
Michael

**Comment by kyleferguson** [comment]
I'm not able to push images to a private GCR repo either, returns same 400 every time. Have tried all sorts of combinations to try and make it work. 

`Error interacting with this repository: gcr.io/* PUT https://gcr.io/v1/repositories/* returned 400`

**Comment by gelidus** [comment]
Is there any progress on this? Running into the same issue, this is my config:

```
deploy:
  box: nginx
  steps:
    - script:
      name: copy nginx config
      code: cp nginx.conf /etc/nginx/nginx.conf

    - script:
      name: copy distro to nginx serve folder
      code: cp -r app/* /usr/share/nginx/html

    - internal/docker-scratch-push:
        username: _json_key
        password: $GCR_JSON_KEY_FILE
        repository: eu.gcr.io/project/image
        registry: https://eu.gcr.io
```

This is what I get:

```
Not allowed to interact with this repository: eu.gcr.io/project/image
```
