### ISSUE TITLE
internal/docker-push to ECR doesn't use env variables from the pipeline

### ISSUE THREAD

**Issue by NZKoz** [wercker/support#221]
The internal/docker-push support for amazon ECR registries doesn't appear to support the environment variables mentioned in #40.  I have my step configured as follows:

```yml
        - script:
            name: determine git short rev
            code: |
                export SHORT_REV_TAG=${WERCKER_GIT_COMMIT:0:7}

        - internal/docker-push:
            disable-sync: true
            aws-access-key: $AWS_ACCESS_KEY_ID
            aws-secret-key: $AWS_SECRET_ACCESS_KEY
            aws-region: us-west-2
            aws-registry-id: $AWS_REGISTRY_ID
            repository: whatever
            tag: $SHORT_REV_TAG,$WERCKER_GIT_BRANCH
```

Expected result:
* image pushed with tags `master` and `c5bf5b0`

Actual result:
* image pushed with master and latest.

Additional information:

- wercker environment: hosted

**Comment by moritzzimmer** [comment]
We would also like to use env vars in the *tag* configuration for the *internal/docker-push* to ECR. For instance to tag the image with the app version. Currently wercker seems to ignore this and sets *latest* instead.

```
- script:
             name: init shell with app version ($VERSION)
             code: |
                source /pipeline/source/data/version.txt
                env
        - internal/docker-push:
              aws-access-key: $AWS_ACCESS_KEY_ID
              aws-secret-key: $AWS_SECRET_ACCESS_KEY
              tag: $VERSION
              ...
```

**Comment by PepijnK** [comment]
This works for me:

```
- internal/docker-push:
      aws-access-key: $AWS_ACCESS_KEY_ID
      aws-secret-key: $AWS_SECRET_ACCESS_KEY
      aws-region: $AWS_REGION
      aws-registry-id: $AWS_REGISTRY_ID
      repository: $MODULE
      disable-sync: true
      volumes: /tmp
      ports: $PORT
      cmd: java -jar -Xms256M -Xmx256M -Djava.awt.headless=true -Djava.security.egd=file:/dev/./urandom /app.jar      
      tag: $WERCKER_GIT_COMMIT
```

**Comment by alextrofymenko** [comment]
@NZKoz I believe in your case that's expected behaviour. Since you're including `disable-sync: true`, all env vars defined inside the container will be ignored: http://devcenter.wercker.com/docs/steps/internal-steps.html#docker-push

**Comment by djMax** [comment]
@NZKoz did removing disable-sync fix it for you? I'm having a similar problem and I don't have disable-sync set to true.

**Comment by devillex** [comment]
I'm having the exact same issue when using 'internal/docker-push' with an alpine based image.

Here is my push pipeline from wercker.yml

```yml
push:
  # use the minimal alpine image with nginx bundled with it
  box:
    id: nginx:stable-alpine
    cmd: /bin/sh
  steps:
    - script:
        name: copy cached build output for nginx to serve
        code: |
          echo contents of current dir \'.\'
          ls -al
          mv build/* /usr/share/nginx/html
          echo contents of nginx serve dir '/usr/share/nginx/html'
          ls -al /usr/share/nginx/html
    - script:
        name: set tag version from cache
        code: |
          source PACKAGE_JSON_VERSION.txt
          echo read version \'$PACKAGE_JSON_VERSION\'
    - script:
        name: set docker image tag
        code: |
          [ "$WERCKER_GIT_BRANCH" = "master" ] \
          && export PACKAGE_VERSION=$PACKAGE_JSON_VERSION \
          || export PACKAGE_VERSION=$WERCKER_GIT_COMMIT
          echo using \'$PACKAGE_VERSION\' as tag

    - internal/docker-push:
        registry: https://gcr.io
        username: _json_key
        password: $GCR_JSON_KEY_FILE
        repository: gcr.io/arctic-eye-468/admin-front-end
        tag: $PACKAGE_VERSION # this is empty, which defaults to latest
```

For reference PACKAGE_JSON_VERSION.txt contains `export PACKAGE_JSON_VERSION=$PACKAGE_VERSION`.
