### ISSUE TITLE
parameterize step name

### ISSUE THREAD

**Issue by xenoterracide** [wercker/support#233]
this is a question perhaps followed with a feature request.

```
 box: maven:latest
build:
  steps:
    - xenoterracide/maven:
        goals: checkstyle:check
    - xenoterracide/maven:
        goals: compile
    - xenoterracide/maven:
        goals: findbugs:check
    - xenoterracide/maven:
        goals: test
deploy:
  steps:
    - xenoterracide/maven:
        settings: settings.xml
        goals: deploy
```

given this yaml the output on the screen will be "maven" "maven" "maven" "maven" without expanding the steps. is there any way to parameterizer the output so that it would print the "goals as well"? if not could we get that please?

**Comment by flenter** [comment]
Sure, you can use `name: ....`

So you could do:
```
box: maven:latest
build:
  steps:
    - xenoterracide/maven:
        name: check style
        goals: checkstyle:check
    - xenoterracide/maven:
        name: compile
        goals: compile
    - xenoterracide/maven:
        name: find bugs
        goals: findbugs:check
    - xenoterracide/maven:
        name: run tests
        goals: test
```
