### ISSUE TITLE
"no such image"  when building Local service

### ISSUE THREAD

**Issue by pitervergara** [wercker/support#242]
`wercker dev` exits with the error **no such image** when building a local service, defined in a second wercker.yml file.

I followed the "Local Services" section of this document: http://devcenter.wercker.com/docs/services/advanced-services.html to add a nginx container to my deploy. Bellow is the folder structure of my project:

```
| (several other files)
|-- .web-container
|   |-- _builds
|   |-- _cache
|   |-- nginx-prd.conf
|   |-- _steps
|   |-- web-prd-entrypoint.sh
|   `-- wercker.yml
`-- wercker.yml       <------------ this is my 'main' wercker file
```

Inside the *main* wercker file I have:
```
dev:
  services:
    - id: mdillon/postgis
      env:
        POSTGRES_USER: some-en-vars-here
    - id: nginx
      url: file://.web-container/#dev
      entrypoint: /entrypoint.sh
      cmd: "nginx -g daemon off;"
  steps:
    - script:
   (all the rest)
```
The .web-container/wercker.yml contains:
```
box: library/nginx

dev:
  steps:
    - install-packages:
      packages: netcat
    - script:
   (all the rest)
```

When I run `wercker dev`, the pipeline fails because it cannot find the image. I have tried some other forms (eg. *nginx*, *nginx:latest*) and also other images (eg. *node*), but the error is the same. If I try using an image that is already pulled, it works.

If I do `cd .web-container`  followed by `wercker dev`to build it directly it also works fine. After the image has been downloaded, I can run wercker-dev from the *root* of my project and the error is gone.

Additional information:

- wercker environment: local
- OS: linux
- Docker environment: native

[gist twith details](https://gist.github.com/pitervergara/7dca6204111e0a1f5d7a72b04087afd4)
