### ISSUE TITLE
store fails to archive/restore some files properly

### ISSUE THREAD

**Issue by qraynaud** [wercker/support#25]
I tried the following script at the end of my build pipeline and at the start of my deploy pipeline as demonstrated:

```yaml
build:
  steps:
  - …
  - script:
      name: test
      code: |
        set -o xtrace
        cat ./node_modules/.bin/gulp
build:
  steps:
  - script:
      name: test
      code: |
        set -o xtrace
        cat ./node_modules/.bin/gulp
  - …
```

And got the following results in build:
```
++ cat ./node_modules/.bin/gulp
#!/usr/bin/env node

'use strict';
var gutil = require('gulp-util');
[…]
```

And in the following deploy:
```
++ cat ./node_modules/.bin/gulp
```

I don't know for sure but I suspect the archiving script fails to load files in "hidden" directories when starting the deployment. It took me a very long time to understand why calling the gulp script was not doing anything.

Good to know : I think it happens during deployment because if I pull the container and cat the file it is there. I'll download my last build just to double check and report though.
