### ISSUE TITLE
Setup environment fails: command timed out after no response

### ISSUE THREAD

**Issue by razor-x** [wercker/support#259]
The third pipeline in my workflow fails on "setup environment" with "Command timed out after no response" (5 minutes, 3 seconds).

I've tried modifying the build steps and even just using

```
push:
  steps:
    - script:
        name: ls
        code: ls -l
```

See https://app.wercker.com/razorx/tasty-pokedex/runs
