### ISSUE TITLE
Support build matrix type of system

### ISSUE THREAD

**Issue by cursork** [wercker/support#26]
I know this is a big feature request, but I'd be **very** happy for something along build matrix lines. In my head this could be as simple as just running the same config against multiple boxes:

e.g. instead of:

```yaml
box:
  id: cursork/foobar
  tag: latest
```

It could be something like this (just a thought!)

```yaml
boxes:
  - name: legacy
    id: cursork/foobar
    tag: legacy
  - name: latest
    id: cursork/foobar
    tag: latest
```

The advantage being this could be any arbitrary base configuration system (more powerful than just selecting a different $programming_language version!)

**Comment by paulbutcher** [comment]
+1

Or, alternatively, is there any way to achieve the same effect with Wercker as it currently stands? If so, some documentation describing the officially sanctioned way to do so would be massively helpful.

**Comment by qraynaud** [comment]
Since you don't have an install step you can easily do so by using a box with the necessary tools to switch between software versions. With node/ruby it could be a VM with nvm/rvm and the following steps:

```yaml
build:
  steps:
  - script:
      name: node 0.10
      code: |
        nvm install 0.10.x
  - npm-test
  
  - script:
      name: node 0.12
      code: |
        nvm install 0.12.x
  - npm-test
```

I'm not sure it can adapt to every scenario easily. Matrixes would be cooler for sure.
