### ISSUE TITLE
virtualenv was not found. It probably is not installed?

### ISSUE THREAD

**Issue by barisc** [wercker/support#27]
Getting this error , I couldn't figure out from documentation and searches online could you please comment on it are my boxes wrong?:
```
export WERCKER_STEP_ROOT="/pipeline/virtualenv-27d51ecb-431f-4e26-ae5e-97a7595ba192"
export WERCKER_STEP_ID="virtualenv-27d51ecb-431f-4e26-ae5e-97a7595ba192"
export WERCKER_STEP_OWNER="wercker"
export WERCKER_STEP_NAME="virtualenv"
export WERCKER_REPORT_NUMBERS_FILE="/report/virtualenv-27d51ecb-431f-4e26-ae5e-97a7595ba192/numbers.ini"
export WERCKER_REPORT_MESSAGE_FILE="/report/virtualenv-27d51ecb-431f-4e26-ae5e-97a7595ba192/message.txt"
export WERCKER_REPORT_ARTIFACTS_DIR="/report/virtualenv-27d51ecb-431f-4e26-ae5e-97a7595ba192/artifacts"
export WERCKER_VIRTUALENV_PYTHON_LOCATION=""
export WERCKER_VIRTUALENV_INSTALL_WHEEL="false"
export WERCKER_VIRTUALENV_VIRTUALENV_LOCATION=""
source "/pipeline/virtualenv-27d51ecb-431f-4e26-ae5e-97a7595ba192/run.sh" < /dev/null
using default python location: /usr/local/bin/python
using default location: /root/venv
failed: virtualenv was not found. It probably is not installed?
```

With this wercker.yaml file in the docker system

```
# This references the default Python container from
# the Docker Hub with the 2.7 tag:
# https://registry.hub.docker.com/_/python/
# If you want to use a slim Python container with
# version 3.4.3 you would use: python:3.4-slim
# If you want Google's container you would reference google/python
# Read more about containers on our dev center
# http://devcenter.wercker.com/docs/containers/index.html
box: python:3.4-slim
# You can also use services such as databases. Read more on our dev center:
# http://devcenter.wercker.com/docs/services/index.html
# services:
    # - postgres
    # http://devcenter.wercker.com/docs/services/postgresql.html

    # - mongodb
    # http://devcenter.wercker.com/docs/services/mongodb.html

# This is the build pipeline. Pipelines are the core of wercker
# Read more about pipelines on our dev center
# http://devcenter.wercker.com/docs/pipelines/index.html
build:
  # The steps that will be executed on build
  # Steps make up the actions in your pipeline
  # Read more about steps on our dev center:
  # http://devcenter.wercker.com/docs/steps/index.html
  steps:
    # A step that sets up the python virtual environment
    - virtualenv:
        name: setup virtual environment
        install_wheel: false # Enable wheel to speed up builds (experimental)

    # # Use this virtualenv step for python 3.2
    # - virtualenv
    #     name: setup virtual environment
    #     python_location: /usr/bin/python3.2

    # A step that executes `pip install` command.
    - pip-install

    # # This pip-install clears the local wheel cache
    # - pip-install:
    #     clean_wheel_dir: true

    # A custom script step, name value is used in the UI
    # and the code value contains the command that get executed
    - script:
        name: echo python information
        code: |
          echo "python version $(python --version) running"
          echo "pip version $(pip --version) running"
```
