### ISSUE TITLE
Failure to push image using "nginx:stable-alpine" - Guest command failed with exit code -1: mkdir -p "/pipeline"

### ISSUE THREAD

**Issue by devillex** [wercker/support#275]
I'm trying to push an image using the minimal 'alpine' build of nginx:stable as a base. Unfortunately it seems that wercker can't use alpine images as it doesn't have permissions to create the "/pipeline" directory.

wercker yml of pipeline:

```yml
push:
  # use the minimal alpine image with nginx bundled with it
  box: nginx:stable-alpine
  steps:
    - script:
      name: copy cached build output for nginx to serve
      code: |
        cp -R $WERCKER_OUTPUT_DIR/ /usr/share/nginx/html
        echo contents of nginx serve dir '/usr/share/nginx/html'
        ls -al /usr/share/nginx/html
    - script:
      name: export version to tag the image with
      code: |
        [ "$WERCKER_GIT_BRANCH" == "master" ] \
        && export PACKAGE_VERSION=$(node -p -e "require('./package.json').version") \
        || export PACKAGE_VERSION=$WERCKER_GIT_COMMIT
    - internal/docker-push:
      registry: https://gcr.io
      username: _json_key
      password: $GCR_JSON_KEY_FILE
      repository: gcr.io/$CLUSTER_NAME/$PROJECT_NAME
      tag: $PACKAGE_VERSION

  after-steps:
    - slack-notifier:
        url: $SLACK_WEBHOOK_URL
        username: wercker
```

I get the following error when the pipeline runs:

> Guest command failed with exit code -1: mkdir -p "/pipeline"

The idea is to build static content to serve in a build step, copy it to the wercker output dir, and then use that to create an image to deploy.

Additional information:

- wercker environment: hosted
- OS: mac
- [Link to failed run](https://app.wercker.com/AdDynamoDevelopment/admin-website-frontend/runs/push-image/580e07047b8e7b010028edd1)

**Comment by akupila** [comment]
The initial creation of `/pipeline` is done with bash by default but alpine doesn't include bash. If you set the `cmd` to `/bin/sh` it should work:

```yml
push:
  # use the minimal alpine image with nginx bundled with it
  box:
    id: nginx:stable-alpine
    cmd: /bin/sh
  steps:
    - script:
      name: copy cached build output for nginx to serve
...
```

See more: http://devcenter.wercker.com/docs/faq/alpine-faq.html
