### ISSUE TITLE
Unable to push container to Heroku

### ISSUE THREAD

**Issue by razor-x** [wercker/support#279]
I'm attempting to push a container to Heroku (see https://devcenter.heroku.com/articles/container-registry-and-runtime). The push step fails with:

```
Error interacting with this repository: registry.heroku.com/my-app-name/web PUT https://registry.heroku.com/v1/repositories/my-app-name/web/ returned 404
```

I'm using this step:

```yaml
- internal/docker-push:
  ports: 80
  repository: registry.heroku.com/my-app-name/web
  tag: $HEROKU_TAG
  username: $HEROKU_USERNAME
  password: $HEROKU_PASSWORD
  registry: https://registry.heroku.com
```
