### ISSUE TITLE
Symlinks not preserved in WERCKER_CACHE_DIR

### ISSUE THREAD

**Issue by twolfson** [wercker/support#280]
Builds have been taking a while for me so I wanted to take a shot at speeding them up. I decided that the time/accuracy trade-off of caching the installed result of `node_modules` is more worth it to me at this time. Unfortunately, symlinks are being converted to 0 size normal files when saving/restoring from cache.

Steps to reproduce:

- Set up a `wercker.yml` with the following content:

```yml
box: ubuntu:14.04
build:
  steps:
    - script:
        name: reproduce issue
        code: |
          # Create and navigate to cache directory
          mkdir -p "$WERCKER_CACHE_DIR/wercker/cache"
          cd "$WERCKER_CACHE_DIR/wercker/cache"

          # Output current contents (empty first, cached second)
          ls -la .

          # Generate our file and symlink
          echo 'foo' > foo
          ln -s foo bar

          # Verify symlink looks good
          cat bar

          # Output new contents
          ls -la .
```

- Run test twice in series

Expected behavior:

- First test has `ls` has no foo/bar, performs setup, then `lrwxrwxrwx. 1 root root    3 Nov  3 20:11 bar -> foo`
- Second test has `lrwxrwxrwx. 1 root root    3 Nov  3 20:11 bar -> foo` before setup

Actual behavior:

- First test has `ls` has no foo/bar, performs setup, then `lrwxrwxrwx. 1 root root    3 Nov  3 20:11 bar -> foo`
- Second test has `-rwxr-xr-x. 1 root root    0 Nov  3 20:15 bar` before setup (i.e. empty normal file, not symlink)

Additional information:

- wercker environment: hosted
- OS: linux
- Docker box: ubuntu:14.04
