### ISSUE TITLE
internal/store-container failing to generate artifacts on wercker site

### ISSUE THREAD

**Issue by birarvin** [wercker/support#292]
Wercker CLI runs fine locally and generates image successfully, but build pipline fails with error "Store Container failed" once yaml is commited to GIT. Has anyone seen this issue before?

```
dev:
    steps:
        - setup-go-workspace:
            package-dir: github.com/birarvin/pipeline
        - script:
            name: env
            code: env
        - script:
            name: go get
            code: |
                cd $WERCKER_SOURCE_DIR
                go version
                go get -u github.com/Masterminds/glide
                export PATH=$WERCKER_SOURCE_DIR/bin:$PATH
                glide install
        - internal/watch:
            code: |
                go run main.go
            reload: true

build:
    # The steps that will be executed on build
    # Steps make up the actions in your pipeline
    # Read more about steps on our dev center:
    # http://devcenter.wercker.com/docs/steps/index.html
    steps:
        # Sets the go workspace and places you package
        # # at the right place in the workspace tree
        - setup-go-workspace:
            package-dir: github.com/birarvin/pipeline

        # Gets the dependencies
        - script:
            name: go get
            code: |
                go get

        # Build the project
        - script:
            name: go build
            code: |
                go build ./...

        # Test the project
        - script:
            name: go test
            code: |
              go test -v $(glide novendor)

        - script: 
            name: copy files to wercker output
            code: |
                cp -R ./ ${WERCKER_OUTPUT_DIR}

        - internal/store-container


````
