### ISSUE TITLE
Support pushing containers to Google Container Registry on Ewok

### ISSUE THREAD

**Issue by vially** [wercker/support#30]
Add support for pushing containers to [Google Container Registry](https://cloud.google.com/tools/container-registry/) on the Ewok infrastructure stack.

**Comment by mies** [comment]
this should now be possible with the information in: https://github.com/wercker/support/issues/40

**Comment by vially** [comment]
Given that the documentation about the gcr.io authentication is rather sparse, maybe it might be a good idea to update the docs with an example of how this could be achieved:
```yaml
deploy:
  box: google/cloud-sdk
  steps:
    - script:
        name: install jq
        code: wget -O /usr/local/bin/jq https://github.com/stedolan/jq/releases/download/jq-1.5rc1/jq-linux-x86_64-static && chmod a+x /usr/local/bin/jq
    - script:
        name: gcr.io authentication
        code: |
          export CLOUDSDK_CORE_DISABLE_PROMPTS=true
          gcloud auth activate-refresh-token $GCLOUD_ACCOUNT $GCLOUD_REFRESH_TOKEN
          gcloud config set project $GCLOUD_PROJECT
          gcloud config set compute/zone $GCLOUD_ZONE
          gcloud preview docker --authorize_only
          export GCR_AUTH_TOKEN=$(cat $HOME/.dockercfg | jq --raw-output '.["https://gcr.io"].auth' | base64 --decode | cut -d ':' -f2)
    - internal/docker-push:
        username: _token
        password: $GCR_AUTH_TOKEN
        repository: gcr.io/example-proj/my-image
        registry: https://gcr.io
```
