### ISSUE TITLE
Can't pull tagged image in deploy phase

### ISSUE THREAD

**Issue by tal-moshayov** [wercker/support#38]
my deploy phase states the following box:
```
deploy:  
  box:  
    id: siloco/silo-box  
    username: $DOCKERHUB_USR  
    password: $DOCKERHUB_PWD  
    tag: $WERCKER_GIT_COMMIT  
```
which yields "no such image". 
**Is the `$WERCKER_GIT_COMMIT` supported in the box section of a deploy phase?**

I also tried the following setup, which fails with `Command exited with exit code: 1`:
```
deploy:
  box:
    id: siloco/silo-box
    username: $DOCKERHUB_USR
    password: $DOCKERHUB_PWD
    tag: 511593bc1189eb4617e0301117ca9ca5bc387275
```
**How can I use a tagged image at the deploy phase?**
