### ISSUE TITLE
Allow internal/docker-push to use env vars defined inside the container

### ISSUE THREAD

**Issue by vially** [wercker/support#40]
Apparently the `internal/docker-push` step only allows **pipeline** variables to be used in the username/password field.

Example:
```yml
deploy:
  steps:
    - script:
        name: gcr.io authentication
        code: export GCR_AUTH_TOKEN=$(obtain_temporary_gcr_io_token)
    - internal/docker-push:
        username: _token
        password: $GCR_AUTH_TOKEN # this value is empty
        repository: gcr.io/my-project/my-image
        registry: https://gcr.io
```

Unfortunately this makes it almost impossible to use with the Google Container Registry (gcr.io) which issues temporary registry auth tokens which expire after some time.

**Comment by karthikkolli** [comment]
+1 

I am trying to push tag with the application version. The value is empty.

- internal/docker-push:
            tag: $APP_VERSION
            ports: XXXX
            repository: XXXX
            registry: https://quay.io

**Comment by mies** [comment]
You are correct. Our goal is to support setting the environment from with the `internal/docker-push` step probably similar to how it's done for a service: http://devcenter.wercker.com/docs/services/mariadb.html

It is possible for instance to set the tag of the container to the `$WERCKER_GIT_COMMIT` environment variable as is done here: https://github.com/wercker/wercker-kubernetes-quay/blob/master/wercker.yml

**Comment by vially** [comment]
Unless I'm misunderstanding something I don't think what you're proposing actually solves my issue. 

My use case right now is simply to be able to use an environment variable defined in a previous `script` step as the `username`, `password` or `tag` field of the `internal/docker-push` step and this does not seem to be supported at the moment.
Right now it seems the `internal/docker-push` step only accepts variables defined from the wercker website (pipeline and/or deploy variables) which is not enough for my use case because the variable I'm trying to use is dynamic (e.g.: changes at build time).

Is this use case supported at the moment? Are there any plans to support it in the future?

**Comment by lindseybateman** [comment]
@vially thanks for clarifying your use case.
Ate the moment this is not supported but is definitely high on our list of features to add.

Will keep you posted.

**Comment by mies** [comment]
Hi all,

We've updated the wercker CLI and our pipeline infrastructure to support that environment variables created during the pipeline are available in both `internal/docker-push` and `internal/docker-scratch-push`. In terms of a `wercker.yml` this would work in the following way:

```yaml
deploy:
  steps:
    - script:
        name: set env
        code: |
          # define environment variables
          export QUAY_USERNAME=<YOUR_USERNAME>
          export QUAY_PASSWORD=<YOUR_PASSWORD>

    - internal/docker-scratch-push:
        # use them in the internal steps
        username: $QUAY_USERNAME
        password: $QUAY_PASSWORD
        cmd: /app
        tag: latest
        ports: "5000"
        repository: quay.io/USERNAME/REPO
        registry: https://quay.io
```

We hope this satisfies your use-case. Will keep this issue open until we hear from you guys.

cheers!
