### ISSUE TITLE
wercker.yml regression on escaping

### ISSUE THREAD

**Issue by qraynaud** [wercker/support#41]
Hi,

I'm using the heroku-deploy step and want to run the following command on heroku using the run argument: `curl -XDELETE $BONSAI_URL/some_suffix`. Since I want the variable to be resolved on the heroku side I need the $BONSAI_URL to be escaped somehow.

Until a few days ago, using a `\` before the `$` was working properly (eg `curl -XDELETE \$BONSAI_URL/some_suffix`) but it does not anymore. What can I do to properly escape the `$`?

**Comment by flenter** [comment]
Are you using the docker enabled infrastructure or classic?

**Comment by qraynaud** [comment]
docker

**Comment by qraynaud** [comment]
Any news on this… I still don't know how to escape $ and it is annoying me…

**Comment by hatchan** [comment]
Can you send me a example of the wercker.yml you are trying to use? Strip out anything private data in the wercker.yml before sending it.

**Comment by qraynaud** [comment]
```yaml
box: node:4.1

build:
  steps:
  - npm-install

  - script:
      name: gulp
      code: |
        ./node_modules/.bin/gulp

  after-steps:
  - turistforeningen/slack-notifier:
      url: $SLACK_URL

deploy:
  steps:
  - script:
      name: gulp deploy
      code: |
        ./node_modules/gulp/bin/gulp.js deploy

  - wercker/heroku-deploy@3.0.0:
      source_dir: $DEPLOY_DIR
      key-name: HEROKU_DEPLOY_KEY
      # my problem is here, it runs "curl -XDELETE \/app_name"
      run: curl -XDELETE \$BONSAI_URL/app_name

  - script:
      name: restart app
      code: |
        heroku restart -a $HEROKU_APP_NAME

  after-steps:
  - turistforeningen/slack-notifier:
      url: $SLACK_URL
```
