### ISSUE TITLE
Permission denied for github private repo fetched via berkshelf

### ISSUE THREAD

**Issue by dgoradia-atlas** [wercker/support#48]
My build uses berkshelf to manage dependencies and one of the dependencies is a private github repo. So on my wercker application I followed the guide: http://blog.wercker.com/2013/12/03/Using-private-repos.html and created a new key, added it to the repo's deploy keys and created a pipeline variable. 

Then added 
```
build:
  steps:
    - add-ssh-key:
        keyname: PREPO_KEY
...
```

But my build output shows
```
...

Warning: Permanently added 'github.com,192.30.252.129' (RSA) to the list of known hosts.
Permission denied (publickey).
...
```

**Comment by ertrzyiks** [comment]
I have similar issue, but for me it occur only on Ewok. See #49

**Comment by rudolfdobias** [comment]
Same issue here, only difference is that we're running bitbucket, not github. Installation key is defined..   
It's two days when this stopped to work without change on our side.

`...                                           
  Warning: Permanently added the RSA host key for IP address '131.103.20.167' to the list of known hosts.                                      
  Permission denied (publickey).
... `

Any ideas?

**Comment by hatchan** [comment]
We're looking into some possible issues due to escaping of environment variables.

**Comment by hatchan** [comment]
We've released a fix for the problem. Please reopen, if it the problem still persist.

**Comment by dgoradia-atlas** [comment]
Same issue persists. Reopening.

**Comment by peterturowskij** [comment]
I experience the same issue with private bitbucket repo.

But seems the issue only appears when generating and adding ssh key-pair environment variable on settings tab. 

It perfectly works when using public key provided while creating new application selecting 'Manually add the deploy keys' option. Hope this helps you spot the bug

**Comment by dgoradia-atlas** [comment]
@peterturowskij I'm not sure we have the same issue. My main private github repo is pulled fine. The error arises because I have another private repository dependency in my Berksfile.

**Comment by dgoradia-atlas** [comment]
Also enabled support.
Owner: atlasdigital
Name: cookbook-kvm
Build ID: #47f9155

**Comment by dgoradia-atlas** [comment]
Any help on this wercker?

**Comment by neolytics** [comment]
@dgoradia I don't know if you resolved this but I struggled with this for a bit but finally resolved it.

I created a deploy key on my private repo, which is a dependency for my core application, added it to the wercker app the same as you described in your OP.  That alone didn't work.  I am using a slim box so I had to install a few other dependencies including openssh-client and git, and add github and its fingerprint to known hosts.

Hopefully this helps.

My wercker file looks like 

```
box: python:2.7-slim
build:
  steps:
    - install-packages:
        packages: git openssh-client
    - add-to-known_hosts:
        hostname: github.com
        fingerprint: 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48
    - add-ssh-key:
        keyname: whatever_you_named_the_key_in_wercker
```

**Comment by agmck** [comment]
Has anyone managed to resolve this issue? I'm having the same issue.

I want to run `git clone --bare` to create a complete backup of my source repo. 

Created a new key pair under Environment Variables tab, added it to the deployment keys section of my repo in bitbucket, then added the `add-ssh-key` step to my wrecker.yml. 

During build, `add-ssh-key` is successful, but the build fails when I try to run git clone:

```
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
Did anyone succeed in adding a key pair to access a private git repo?

**Comment by neolytics** [comment]
@agmck I think there are a number of approaches that have resolved this problem.  We deploy private repos daily with wercker.  My comment from January 19th was sufficient to resolve this issue on my end, each piece of the example Yaml I posted was required, including adding github's public key's to my known hosts file.

**Comment by agmck** [comment]
@neolytics much appreciated! Terrific. This did the trick — 
```
- add-to-known_hosts:
    hostname: bitbucket.org
    fingerprint: 97:8c:1b:f2:6f:14:6b:5c:3b:ec:aa:46:46:74:7c:40
    type: rsa
```
