### ISSUE TITLE
Making use of WERCKER_CACHE_DIR

### ISSUE THREAD

**Issue by boedy** [wercker/support#50]
Hi I've been playing with Wercker for the last two weeks. Really liking it! Took me a while though to get everything setup and running.

I want to use Wercker to deploy our PHP application to AWS Elastic beanstalk. I got everything to work, but every time I deploy all my dependencies need to be pulled in again with composer, which slows down the process by 60 to 90 seconds. I've read that it's possible to use the WERCKER_CACHE_DIR environment variable to speed up this process. I've used the following pages as reference: 

- http://blog.wercker.com/2013/07/25/improving-Go-build-time-with-wercker-cache.html
- https://github.com/wercker/box-php/blob/master/wercker-box.yml
- https://github.com/leipert/wercker-step-composer-install/blob/master/run.sh

I've been trying a couple of things, but can't get it work. Every time I deploy it again starts to download all dependencies.

I hope someone can point me in the right direction. 

This is my wercker.yml file

```
box: boedy/wercker-php
build:
  steps:
    - script:
        name: install dependencies
        code: |
          cd src
          composer config --global cache-dir $WERCKER_CACHE_DIR/composer
          composer self-update
          composer install
deploy:
  box:
      id: quay.io/kollekt/eb-deploy
      username: $QUAY_USERNAME
      password: $QUAY_PASSWORD
      registry: https://quay.io
  steps:
    - script:
        name: add new version to elastic beanstalk
        code: |
          mkdir /root/.aws
          printf '[default]\naws_access_key_id = %s\naws_secret_access_key = %s\n' $AMAZON_KEY $AMAZON_SECRET_KEY >> /root/.aws/credentials
          printf '[default]\nregion = %s\n' $AWS_REGION >> /root/.aws/config
          RELEASE_FILE=$WERCKER_GIT_COMMIT.zip
          #sed "s/<TAG>/$WERCKER_GIT_COMMIT/" < Dockerrun.aws.json.dist > Dockerrun.aws.json
          zip -r $RELEASE_FILE Dockerrun.aws.json .ebextensions src config
          aws s3 cp $RELEASE_FILE s3://$AWS_S3_BUCKET/$RELEASE_FILE
          aws elasticbeanstalk create-application-version --application-name $BEANSTALK_APPLICATION --version-label $WERCKER_GIT_COMMIT --source-bundle S3Bucket=$AWS_S3_BUCKET,S3Key=$RELEASE_FILE
    - script:
        name: deploy new version
        code: aws elasticbeanstalk update-environment --environment-name $BEANSTALK_ENVIRONMENT --version-label $WERCKER_GIT_COMMIT
```

**Comment by jimhester** [comment]
The cache is not avaiable with ewok builds, only the classic stack (unless something has changed, I am not associated with wercker).  See http://devcenter.wercker.com/docs/cache/

**Comment by mies** [comment]
Caching is definitely on the roadmap and one of the first things we'll be releasing in the near future!

**Comment by statianzo** [comment]
Cache would be wonderful. Been testing out ewok against a rails app and the `bundle install` time is killing me. Everything else about ewok has rocked though, great work!

**Comment by hatchan** [comment]
@statianzo Caching is coming to ewok this week

**Comment by boedy** [comment]
:+1:

**Comment by xenoterracide** [comment]
is/will there updated caching docs? I imagine that using it with docker isn't the same as before? probably as mounting a data volume somehow?

**Comment by xenoterracide** [comment]
reading the updated docs and announcement, I don't notice that it's working for my maven step. A second run doesn't retain the data.

https://bitbucket.org/xenoterracide/wercker-step-maven/src/8635320dd8ba63099078fac3bee099c717a47617/run.sh?at=master

**Comment by Tonnu** [comment]
@xenoterracide could you turn on support for your application? You can enable it through the application settings. It could be that your cache is too big (the limit being 1 gig).

**Comment by xenoterracide** [comment]
that doesn't seem like that'd be my problem, though my problem seems to have gone away now... Maybe the change hadn't fully gone out yet or something?

**Comment by fruitl00p** [comment]
Is this still accurate? (after a quick google i came to this issue)

In my wercker.yml i have the following:
```yml
box: gekkie/wercker-docker-php:5.6
build:
  steps:
    - script:
        name: download the depencies
        code: |
          composer config --global cache-dir $WERCKER_CACHE_DIR/composer
          composer install

    - script:
        name: PHPUnit integration tests
        code: phpunit
```
How do i get the cache-dir to actually work? I've now had the unfortunate situation that the limitation has been reached for fast downloads and it's reverted to git cloning... 

(btw the box used is a simple php+composer+git(+phpunit) box...

**Comment by maryo** [comment]
Looks like it works for me.

```
- script:
    name: configure composer cache
    code: |
        mkdir $WERCKER_CACHE_DIR/composer || true
        composer config --global cache-dir $WERCKER_CACHE_DIR/composer
- script:
    name: install dependencies
    code: composer install --prefer-dist --no-interaction
```

I am not sure if the mkdir is needed anymore since the directory already exists :)
