### ISSUE TITLE
wercker-api resource not found

### ISSUE THREAD

**Issue by captn3m0** [wercker/support#61]
I am using the latest cli:

```
$ wercker version
Version: 1.0.152
Compiled at: 2015-06-02 16:24:01 +0530 IST
Git commit: f98fade43d1fee1f9fe5225fb82688216ce89836
No new version available
```

wercker dev just fails:

```
wercker dev
--> Executing pipeline
--> Running step: setup environment
Pulling from php: latest
Already exists: 64e5325c0d9d
Already exists: bf84c1d84a8f
Already exists: addf6a6a564c
Already exists: 7aa4041d8445
Already exists: dfb0928bb61e
Already exists: da3d2c32f45c
Already exists: 1d17ea5b176f
Already exists: 039ecb1b93df
Already exists: 7be30c50561b
Already exists: fad6d1fc29de
Already exists: 9c4c11b0e36f
Already exists: 2fd8dd167b17
Already exists: 2fd8dd167b17
Digest: sha256:380885841aa25ab0c03a7ca3d8812bff87bf33e8fef95e63aa8559f071935858
Status: Image is up to date for php:latest
ERROR --> Step failed: setup environment
wercker-api: resource not found (status code: 404)
ERROR wercker-api: resource not found (status code: 404)
```

**Comment by flenter** [comment]
Can you also display the `wercker.yml` you're using?

**Comment by captn3m0** [comment]
I got the same issue on the build on the wercker infra just now:

https://app.wercker.com/#buildstep/5589502dbe159c0a7500fd0c

I have enabled support in the settings, so you should have access.

**Comment by hatchan** [comment]
Indent the arguments of the steps by 2 more spaces, that should fix this issue

**Comment by flenter** [comment]
Also: apart from the slack notify step, you probably want to change all steps into script steps instead of the unique names they have now.

```
build:
  steps: 
    - script:
         name: my example step
         code: |
           sleep 10
```
instead of 
```
build:
  steps: 
    - example-step:
         name: my example step
         code: |
           sleep 10
```
