### ISSUE TITLE
after-step slack-notifier is not run

### ISSUE THREAD

**Issue by boris317** [wercker/support#68]
I can't seem to get slack notifications working for my deploys. I've stripped my `wercker.yml` down to try and debug the issue.  The deploy passes but the after-steps are greyed and do not run

```
box: python:2.7

build:
  steps:

    - script:
        name: Dump env vars
        code: env

deploy:

  steps:

    - script:
        code: hostname

  after-steps:
    - slack-notifier:
        url: $SLACK_URL
        channel: $SLACK_CHANNEL
        username: $SLACK_USER
```

<img width="508" alt="screen shot 2015-07-09 at 9 34 32 am" src="https://cloud.githubusercontent.com/assets/339231/8596506/d4f558a8-261d-11e5-8c9e-4ff58c503347.png">
