### ISSUE TITLE
Internal step docker push fails?

### ISSUE THREAD

**Issue by Schnueggel** [wercker/support#75]
I try to push a container to a private registry (V1) with the step internal/docker-push

```yaml
build:
  box: postgres
  steps:
    - script:
        name: make dirs
        code: |
          mkdir /var/lib/postgresql/dump
          cp ./scripts/initdb.sh /docker-entrypoint-initdb.d/
          cp -r ./scripts /scripts
          cp -r ./changelogs /changelogs
deploy:
  box: ubuntu:latest
  steps:
    - internal/docker-push:
        username: $MY_REGISTRY_USER
        password: $MY_REGISTRY_PASSWORD
        repository: $MY_REGISTRY_USER/$MY_DB_REPO
        tag: latest
        registry: $MY_REGISTRY
```

The docker push steps completes successful

But shows this message

```
Pushing to registry
Buffering to Disk: 0b455e5ee562
Image push failed: 0b455e5ee562
```

When I execute the following I cannot find a build image anywhere
```
ls -R /pipeline
```

The image gets pushed to the registry but its somehow incomplete and has no tag.

When I do 
```
docker tag
docker push
```
from a remote commandline to the registry everything works as expected.
