### ISSUE TITLE
2 is being converted to false

### ISSUE THREAD

**Issue by xenoterracide** [wercker/support#81]
both are copied from the logs that wercker outputs
~~~
Using config:
box: maven:latest
build:
  steps:
    - xenoterracide/maven:
        goals: test
deploy:
  steps:
    - xenoterracide/maven:
        debug: 2
        settings: settings.xml
        goals: deploy

Pulling from maven: latest
~~~

somehow this is being translated to

~~~
export WERCKER_MAVEN_DEBUG="false"
export WERCKER_MAVEN_SETTINGS="settings.xml"
export WERCKER_MAVEN_GOALS="deploy"
~~~

how is 2 becoming false?

**Comment by hatchan** [comment]
This is a known issue. Current workaround is to wrap the value in quotes to force it as an string:

```yaml
build:
  steps:
    - xenoterracide/maven:
        goals: test
deploy:
  steps:
    - xenoterracide/maven:
        debug: "2"
        settings: settings.xml
        goals: deploy
```
